### ISSUE TITLE
Error during training: Can't pickle local object 

### ISSUE THREAD

**Issue by DominiqueLade** [minimalist-nlp/lightning-text-classification#2]
Hi,

I really like how you combined PyTorch Lightning with the Transformers library. I tried to upgrade all dependencies to the latest version. There are some smaller issues, like renamed keyword arguments in PyTorch Lightning and so on. Eventually, I face the following error message.

**Error:**
AttributeError: Can't pickle local object 'LayerSummary._register_hook.<locals>.hook'

**Environment:**
python = "^3.7"
torch = "^1.5.1"
torchvision = "^0.6.1"
transformers = "^2.11.0"
pytorch-lightning = "^0.8.1"
pytorch-nlp = "^0.5.0"
test-tube = "^0.7.5"
pandas = "^1.0.5"
sklearn = "^0.0"

Do you have any idea what the error might be? Is it a Lightning problem or a transformers problem? Any way to fix it?

Best
Dominique

**Comment by ricardorei** [comment]
Hey Dominique, sorry for the late reply. This is a Lightning problem for sure: [LayerSummary](https://pytorch-lightning.readthedocs.io/en/latest/api/pytorch_lightning.core.memory.html?highlight=LayerSummary#pytorch_lightning.core.memory.LayerSummary)

You can disable it by:
```python
# don't print a summary
trainer = Trainer(weights_summary=None)
```

It is not the first time I face a "can't pickle error" in lightning.

Actually both Transformers and Lightning have been changing their API's a lot lately. I'll try to do a new update for this repo with Transformers >3.0 and lightning >0.9. Stay tuned!

**Comment by DominiqueLade** [comment]
Thanks for the update! Can't wait for the new version! :)
